### ISSUE TITLE
Crear cartel para la presentación

### ISSUE THREAD

**Issue by jlgarridol** [jlgarridol/TFG-SmartBeds#113]

**Comment by jlgarridol** [comment]
[Prototipo de cartel](https://github.com/jlgarridol/TFG-SmartBeds/files/3361536/NuevoDocumento.2019-07-04.14.54.50.pdf)

**Comment by jlgarridol** [comment]
![Prototipo de cartel](https://user-images.githubusercontent.com/14005926/60704989-47848c80-9f06-11e9-8279-3ffe3fd0a509.png)

**Comment by jlgarridol** [comment]
El hilo conductor sería:

Primero presento los datos, hago una referencia al desbalanceo de los mismos y comento como se distribuyen de manera natural.

A la parte derecha se pondría un gráfico basado en los PCA (algo más bonito) donde se pueda ver que las crisis son subconjuntos de crisis y las crisis no comparten espacio, todo esto me daría pie a decir que los datos originales (independientemente de su filtrado) no tienen una distribución que permita predecir nuevas crisis.

Tras esto se pasa a hacer una referencia a la extracción de características de Alicia, donde aplicamos a sus datos a sistemas de balanceo (presentarlos sucintamente) y los ensembles (presentalos sucintamente), si se viese tiempo mencionar que boosting no fue probado porque las primeras aproximaciones nunca clasificaba bien siqueira el conjunto de entranamiento.

Por último explicar la aplicación, primero el flujo de los datos para su procesamiento en tiempo real, y luego la API de manera general (operaciones CRUD y socketio), con algunas imágenes de la aplicación como referencia

**Comment by jlgarridol** [comment]
Tras trabajar ayer todo el día el resultado fue
![TFG_Cartel-1](https://user-images.githubusercontent.com/14005926/60705575-c1694580-9f07-11e9-9221-8bdf932286e6.png)

**Comment by jlgarridol** [comment]
Algunas modificaciones del tamaño de la cabecera bajo la recomendación de terceros
![TFG_Cartel](https://user-images.githubusercontent.com/14005926/60707113-4013b200-9f0b-11e9-9aed-1d30413ba737.png)

**Comment by alvarag** [comment]
Igual la cabecera queda un poco "amontonada", tal vez se puede hacer un poco más pequeño lo de las presiones y crissi para que haya un poco más de aire ahí arriba.

en general me parece que esta bien

**Comment by jlgarridol** [comment]
He hecho más pequeña la cabecera ya cambiado la fuente de los títulos por una con serifa
![TFG_Cartel-Otros titulos](https://user-images.githubusercontent.com/14005926/60754454-50965c00-9fe1-11e9-89c3-ef84afd7b961.png)

**Comment by alvarag** [comment]
En vez de TFG encima de tu nombre pondría: Autor.

Por lo demás lo veo bien.
