### ISSUE TITLE
Testear clasificadores con otras crisis

### ISSUE THREAD

**Issue by jlgarridol** [jlgarridol/TFG-SmartBeds#33]

**Comment by jlgarridol** [comment]
Los resultados son siempre negativos con la segunda crisis

**Comment by alvarag** [comment]
:(

**Comment by jlgarridol** [comment]
Lo mismo ocurre con la tercera crisis. Para el siguiente sprint sería interesante entrenar el one-class con las dos primeras y testear con la tercera.
