### ISSUE TITLE
Investigar sobre desequilibrados

### ISSUE THREAD

**Issue by joseFranciscoDiez** [jlgarridol/TFG-SmartBeds#39]
Papers a leer
- [x] Galar, Mikel, et al. "A review on ensembles for the class imbalance problem: bagging-, boosting-, and hybrid-based approaches." IEEE Transactions on Systems, Man, and Cybernetics, Part C (Applications and Reviews) 42.4 (2012): 463-484.

- [x] Díez-Pastor, José F., et al. "Random balance: ensembles of variable priors classifiers for imbalanced data." Knowledge-Based Systems 85 (2015): 96-111.

- [x] Díez-Pastor, José F., et al. "Diversity techniques improve the performance of the best imbalance learning ensembles." Information Sciences 325 (2015): 98-117.

**Comment by jlgarridol** [comment]
Por lo que he podido llegar a entender podría ser interesante hacer un SMOTE a los datos de crisis que tenemos porque a pesar de estar quitando una gran cantidad de datos de no crisis el desbalanceo sigue siendo muy alto. Parece que es muy buen método según he leido.

Para hacer la pelota al otro tutor podría ser interesante combinar los ensembles con una selección de instancias sobre los datos de nos crisis para solamente quedarnos con las mas características.

**Comment by alvarag** [comment]
> Para hacer la pelota al otro tutor podría ser interesante combinar los ensembles con una selección de instancias sobre los datos de nos crisis para solamente quedarnos con las mas características.

No hace falta hacer la pelota ;)
