### ISSUE TITLE
Aprender Weka

### ISSUE THREAD

**Issue by joseFranciscoDiez** [jlgarridol/TFG-SmartBeds#40]
Ver
https://www.youtube.com/user/WekaMOOC

**Comment by jlgarridol** [comment]
Podemos utilizar weka desde gamma?, mi ordenador se resiente un poco

**Comment by alvarag** [comment]
Por supuesto, gamma está para nuestro uso y disfrute

**Comment by jlgarridol** [comment]
Genial, como podemos ejecutarlo? Se que es con el flag -X en la conexión, pero no se como instalar weka en linux con terminal sin apt.

**Comment by alvarag** [comment]
Weka es una aplicación en Java, con descargar, descomprimir y ejecutar es suficiente: no necesita instalación

**Comment by jlgarridol** [comment]
> Weka es una aplicación en Java, con descargar, descomprimir y ejecutar es suficiente: no necesita instalación

Genial saberlo, lo acabo de descargar de https://netix.dl.sourceforge.net/project/weka/weka-3-8/3.8.3/weka-3-8-3.zip y según parece java no está instalado

**Comment by alvarag** [comment]
Pensé  que estaba instalado, prueba y confirma que ya puedes usarlo

**Comment by jlgarridol** [comment]
> Pensé que estaba instalado, prueba y confirma que ya puedes usarlo

![image](https://user-images.githubusercontent.com/14005926/53560498-c75fac00-3b4c-11e9-939e-5b93ec24a26f.png)
Ya está funcional, muchas gracias
