### ISSUE TITLE
Filtrado SMOTE

### ISSUE THREAD

**Issue by jlgarridol** [jlgarridol/TFG-SmartBeds#43]
Filtrado SMOTE con Weka con los tres días registrados con crisis con preprocesado estadístico (media y desviación) de tamaño 90

**Comment by jlgarridol** [comment]
Se recibe un OutOfMemoryError: Java heap space
```java
Exception in thread "Thread-13" java.lang.OutOfMemoryError: Java heap space
	weka.filters.supervised.instance.SMOTE.doSMOTE(SMOTE.java:560)
	weka.filters.supervised.instance.SMOTE.batchFinished(SMOTE.java:489)
	weka.filters.Filter.useFilter(Filter.java:708)
	weka.gui.explorer.PreprocessPanel$22.run(PreprocessPanel.java:888)

	at weka.filters.supervised.instance.SMOTE.doSMOTE(SMOTE.java:560)
	at weka.filters.supervised.instance.SMOTE.batchFinished(SMOTE.java:489)
	at weka.filters.Filter.useFilter(Filter.java:708)
	at weka.gui.explorer.PreprocessPanel$22.run(PreprocessPanel.java:888)
```

**Comment by jlgarridol** [comment]
Se ha realizado utilizando una sola crisis (la tercera) aplicando smote con un porcentaje de 1.000 % teniendo aproximadamente así una instancia de crisis por cada 4 instancias de no crisis

**Comment by alvarag** [comment]
Se puede ejecutar la máquina virtual de Java con más memoria (por defecto son 256 MB si no recordamos mal).
https://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvms

**Comment by jlgarridol** [comment]
Lo he estado usando y ya funciona todo, voy a generar para los distintos datasets (crisis individuales, las tres crisis y las dos primeras) al 1.000 % de nuevas instancias
