### ISSUE TITLE
Documentación de resultados

### ISSUE THREAD

**Issue by jlgarridol** [jlgarridol/TFG-SmartBeds#60]

**Comment by alvarag** [comment]
Adjunto comentarios sobre la memoria y anexos.
[anexos_AAG.pdf](https://github.com/joselucross/TFG-SmartBeds/files/3116147/anexos_AAG.pdf)
[memoria_AAG.pdf](https://github.com/joselucross/TFG-SmartBeds/files/3116148/memoria_AAG.pdf)
